const assert=require('node:assert/strict'),fs=require('node:fs');
const css=fs.readFileSync('app/web/assets/dating.css','utf8');
const js=fs.readFileSync('app/web/assets/dating.js','utf8');
const theme=fs.readFileSync('app/web/assets/theme.css','utf8');
assert(theme.includes(':not(:where(#dating .dating-tabs button, #dating .dating-actions button, #dating .dating-photo-nav button,'));
assert(!css.includes('flatOverride'),'Dating controls must not need specificity hacks');
const html=fs.readFileSync('app/web/index.html','utf8');
assert(html.includes('/assets/dating.css?v=photo-overlay-2'));
assert(html.includes('/assets/dating.js?v=photo-overlay-2'));
const routes=fs.readFileSync('app/dating.py','utf8');
for(const [file,type] of [['dating.js','application/javascript'],['dating.css','text/css']]){
  assert(routes.includes("'web/assets/"+file+"', media_type='"+type+"', headers={'Cache-Control': 'no-cache'}"),'Dating assets must revalidate browser cache');
}
assert(!css.includes('nav#nav'),'Dating styles must not modify bottom navigation');
assert(css.includes('#dating{position:relative;z-index:0;isolation:isolate;'),'Fullscreen card layers must stay inside the dating stacking context, below navigation');
assert(!css.includes('58dvh')&&!css.includes('100dvh - 320px'),'Old card height overrides must be removed');
assert(css.includes('#dating .dating-card{position:fixed;inset:0'));
assert(css.includes('#dating:has(.dating-card) .dating-tabs{position:fixed'));
assert(css.includes('bottom:calc(198px + env(safe-area-inset-bottom,0px))'));
assert(css.includes('bottom:calc(116px + env(safe-area-inset-bottom,0px))'));
assert(js.includes('dating-photo-bars'));
assert(css.includes('width:20px;flex:0 1 20px'));
assert(js.includes('bounds.width/2?1:-1'));
assert(js.includes('Math.abs(dx)>10||Math.abs(dy)>10'),'Scrolling must not change photos');
assert(css.includes('width:min(100%,252px)'));
assert(css.includes('top:-15px'));
assert(js.includes('app.HapticFeedback.selectionChanged()'));
assert(css.includes('var(--tab-index)'));
assert(js.includes("style.setProperty('--tab-index',index)"));
assert(js.includes('class="like" aria-label="Yoqtirish"'));
assert(js.includes("api('dating/vote/'+p.id,{liked:!!i})"),'Voting behavior must remain unchanged');
console.log('PASS: dating-only overlay layout and existing vote behavior');
