const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const scope=vm.createContext({});vm.runInContext(fs.readFileSync('app/web/assets/badges.js','utf8'),scope);
const badge=scope.badgeMarkup;
assert.equal(badge({silver:0,gold:0,verified:false}),'');
assert.match(badge({silver:1}),/badge-silver/);
assert.match(badge({silver:30,gold:1}),/badge-gold/);
assert.ok(!badge({silver:30,gold:1}).includes('badge-silver'));
assert.ok(!badge({silver:30,gold:30}).includes('badge-blue'));
assert.match(badge({verified:true}),/badge-blue/);
assert.match(badge({gold:30,verified:true}),/badge-gold.*badge-blue/);
assert.equal(badge({anonymous:true,gold:30,silver:30,verified:true}),'');
const page=fs.readFileSync('app/web/index.html','utf8');
assert.ok(!page.includes('Premium'));
assert.ok(!page.includes('/verify'));
assert.ok(!page.includes('Ko‘k galochka'));
const admin=fs.readFileSync('app/web/admin.html','utf8');
assert.ok(admin.includes('value="silver"'));
assert.ok(admin.includes('Ko‘k galochka berish'));
console.log('PASS: Silver/Gold/blue rendering, tier precedence, anonymous hiding, admin-only controls');
