const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let now=1;
const timers=[];
const animations=[];
const track={children:[],style:{},append(node){this.children.push(node)},replaceChildren(){this.children=[]},animate(frames,options){animations.push(options);return {cancel(){},pause(){}}}};
const status={textContent:''},viewport={clientWidth:384,append(){}};
const classes=new Set();
const panel={hidden:true,classList:{add(name){classes.add(name)},remove(name){classes.delete(name)}},querySelector(selector){return selector==='.roulette-track'?track:selector==='.roulette-window'?viewport:status}};
let divs=0;
const scope=vm.createContext({window:{roulettePeople:[{name:'Preview'}]},document:{head:{append(){}},body:{classList:{add(){}}},createElement(tag){return tag==='div'&&divs++===0?panel:{}}},
  $:()=>({before(){}}),avatar:p=>p.anonymous?'MASK':'AVATAR',esc:x=>x,badgeMarkup:()=>'',performance:{now:()=>now},matchMedia:()=>({matches:false}),getComputedStyle:()=>({transform:'matrix(1,0,0,1,-300,0)'}),
  setTimeout(fn,delay){timers.push({fn,delay});return timers.length},clearTimeout(){}});
vm.runInContext(fs.readFileSync('app/web/assets/roulette.js','utf8'),scope);
(async()=>{
  const roulette=scope.window.chatRoulette;
  roulette.start();
  assert(track.children[24].innerHTML.includes('Preview'));
  assert.notEqual(animations.at(-1).iterations,Infinity);
  assert.equal(animations.at(-1).duration,3000);
  assert(!track.children[24].innerHTML.includes('MASK'));
  roulette.setPeople([{name:'Offline preview'}]);
  assert(track.children[24].innerHTML.includes('Offline preview'));
  now=5000;
  timers.at(-1).fn();
  assert(classes.has('roulette-is-waiting'));
  assert.equal(status.textContent,'Mos suhbatdosh qidirilmoqda…');
  let opened=false;
  const ready=roulette.ready({name:'Actual partner'}).then(()=>opened=true);
  assert(track.children[24].innerHTML.includes('Actual partner'));
  assert(!classes.has('roulette-is-waiting'));
  assert.equal(animations.at(-1).duration,600);
  assert.notEqual(animations.at(-1).iterations,Infinity);
  roulette.setPeople([{name:'Another preview'}]);
  assert(track.children[24].innerHTML.includes('Actual partner'));
  assert.equal(opened,false);
  assert.equal(timers.at(-1).delay,600);
  now+=600;timers.at(-1).fn();await ready;
  assert.equal(opened,true);
  assert.equal(roulette.hold({name:'Actual partner'}),false);
  roulette.reset();assert.equal(panel.hidden,true);
  scope.window.roulettePeople=[];
  roulette.start();
  assert(track.children.every(node=>node.innerHTML.includes('roulette-placeholder')&&!node.innerHTML.includes('MASK')));
  roulette.hold({name:'Hidden partner',anonymous:true});
  assert(track.children[24].innerHTML.includes('MASK'));
  assert(track.children[24].innerHTML.includes('Anonim'));
  roulette.reset();
  console.log('PASS: finite preview spin, waiting state, confirmed landing, reset');
})().catch(error=>{console.error(error);process.exitCode=1});
